import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-[1024px] mx-auto">
        <h1>タイトル</h1>
        <div>
          <ul className="flex">
            <li className="z-0 hover-container inline-block relative">
              <span>ガイド</span>
              <Image
                className="absolute bottom-0 left-0 block"
                src={"/bg_bdb02.png"}
                height={50}
                width={100}
                alt=""
              />
              <Image
                className="hover-image absolute bottom-[-2.5px] left-0 hidden"
                src={"/bg_bdb02.png"}
                height={50}
                width={100}
                alt=""
              />
            </li>
            <li className="group">
              <span className="transition-all duration-200 ease-in-out hover:shadow-top h-10 w-20 hover:bg-white">
                ホバーして
              </span>
              <div className="z-20 hidden group-hover:block duration-200 bg-red-500 h-20 w-[100px]"></div>
            </li>
          </ul>
        </div>
      </main>
    </>
  );
}
